### PR TITLE
Add WebP codec support to libtiff

### PR DESCRIPTION
**Pull request by hobu**
Adding WebP support to allow applications like GDAL to read and compress WebP TIFF content. It was prompted by https://rasterio.groups.io/g/main/message/383

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hobu** [comment]
BTW, according to the Changelog, I think the CVE patches applied in this recipe are fixed in libtiff 4.1.0.

https://gitlab.com/libtiff/libtiff/blob/master/ChangeLog#L1175

**Comment by hobu** [comment]
We are currently failing due to a circular dependency. libwebp is depending on [libtiff on unix](https://github.com/conda-forge/libwebp-feedstock/blob/master/recipe/meta.yaml#L27), and this will have to be resolved before this PR can be applied.

**Comment by ocefpaf** [comment]
> We are currently failing due to a circular dependency. libwebp is depending on [libtiff on unix](https://github.com/conda-forge/libwebp-feedstock/blob/master/recipe/meta.yaml#L27) [](/conda-forge/libwebp-feedstock/blob/HEAD@{2019-12-22T15:08:46Z}/recipe/meta.yaml#L27), and this will have to be resolved before this PR can be applied.

From @hobu's gitter message:

    I think this recipe needs to be broken into two parts – the libwebp code
    part that has no dependencies and a part with all of the utilities like
    img2webp that can depend on the image libraries.

I'm +1 to that but I don't have the time to try it until mid-January. Do you want to try to implement that?

**Comment by hobu** [comment]
What is the strategy to split apart the libwebp recipe? Is there an example to follow?

**Comment by ocefpaf** [comment]
> What is the strategy to split apart the libwebp recipe? Is there an example to follow?

I usually recommend `matplotlib` and `gal` recipes for that. I'll try that later today and report back on the `libwebp` recipe.

**Comment by ocefpaf** [comment]
Needs https://github.com/conda-forge/libwebp-feedstock/pull/24

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
