### PR TITLE
Fixup tests for OSX

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@ocefpaf can we merge this one too? it just fixes the downstream tests for OSX that were failing before.

Thanks @isuruf for finding the source of the problem.

**Comment by isuruf** [comment]
Downstream tests should use https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests to avoid cycles.

**Comment by hmaarrfk** [comment]
will that simply run the downstream `test` section? I should remove the custom commands and file I added right?

**Comment by isuruf** [comment]
yes to both

**Comment by hmaarrfk** [comment]
Does opencv need to be rerendered?https://github.com/conda-forge/opencv-feedstock/issues/220

**Comment by isuruf** [comment]
Yes. Looks like it. There's also an issue with conda-build at https://github.com/conda/conda-build/issues/3908

**Comment by hmaarrfk** [comment]
yeah, this isn't really that good, it defaulted to a really old version of opencv 3.4 (3.4.2) which I don't think you or I maintain.

**Comment by hmaarrfk** [comment]
Lets try again when: https://github.com/conda-forge/opencv-feedstock/pull/221

merges

**Comment by hmaarrfk** [comment]
opencv was merged, but no job is running on master?

**Comment by hmaarrfk** [comment]
@isuruf I really can't understand the conflict, but maybe i'm missing something.

What is the way forward? Do I comment out the opencv test and rebuild opencv when this is pulled in?

**Comment by ocefpaf** [comment]
@hmaarrfk sorry, I let slip through the cracks. Do you still want to rebase it? If not I can try to fix this PR so we can work on the latest version.

**Comment by hmaarrfk** [comment]
honestly, i'm really not sure what the current status of the feedstock is. 

Would have to redo this work. Maybe lets leave it open until one of us has a chance to do it.?

**Comment by ocefpaf** [comment]
> Maybe lets leave it open until one of us has a chance to do it.?

Tried and failed miserably :smile: 

I'll try to find more time and tackle this again later this week. Thanks!

**Comment by hmaarrfk** [comment]
I just manually copied over the idea of the changes.

**Pull request closed without merging**
