### PR TITLE
bump build numbers

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@hmaarrfk are done with the PR? Merge? :wink:

**Comment by hmaarrfk** [comment]
no, i want to get osx to pass.
but seems my test sucks with it.

**Comment by hmaarrfk** [comment]
i just skipped tests for osx, since the patch only affects windows.

It seems that some patch has been accepted upstream. so we'll have to see what happens.

**Comment by ocefpaf** [comment]
> It seems that some patch has been accepted upstream. so we'll have to see what happens.

Cool! Merge?

**Comment by hmaarrfk** [comment]
yeah.

**Pull request merged**
