### PR TITLE
Update to 4.0.8 to incorporate large numbers of security fixes

### PR DESCRIPTION
**Pull request by qwhelan**
The last couple releases of ```libtiff``` have largely been security fix related - this PR pulls in those fixes.

Release notes for the last two releases can be found here:
 - http://www.simplesystems.org/libtiff/v4.0.7.html
 - http://www.simplesystems.org/libtiff/v4.0.8.html

I have also re-rendered the feedstock.

### CODE REVIEW

**Comment by qwhelan** [comment]
It appears that the ```def_snprintf.patch``` file is no longer necessary due to this commit: https://github.com/vadz/libtiff/commit/f69ea7d9a8905753bccc40faa0f3eafcb1b8f78f

**Comment by jakirkham** [comment]
Could you please rebase to resolve conflict? Re-rendering and the patch removal should already be handled at this point.

**Comment by jakirkham** [comment]
Note to others: libtiff 4.0.8 adds 3 new symbols. So we will want to recheck are pinnings and possibly repinning everything before this goes in.

API/ABI report: https://abi-laboratory.pro/tracker/timeline/libtiff/

**Comment by ocefpaf** [comment]
Done in #27. Thanks @qwhelan!

**Pull request closed without merging**
