### PR TITLE
Patching up 4.1 for pillow compatibility on windows

### PR DESCRIPTION
**Pull request by hmaarrfk**
This is a second attempt at fixing some windows incompatibility with Pillow that is definitely affecting some of our users since the 4.1 migration

conda-forge/lcms2-feedstock#3 (comment)
My previous attempt didn't include downstream completeness tests and so I was testing the finished product on the user's end machine.
https://github.com/conda-forge/libtiff-feedstock/pull/49
Which caused some failures to occur downstream.

Talking to @cgohkle the easiest thing to do is simply to build the package the same unintended way the upstream developers had been doing it prior to 4.1

https://github.com/python-pillow/Pillow/issues/4237#issuecomment-570757948

xref:https://github.com/hmaarrfk/libtiff-feedstock/pull/1

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by patricksnape** [comment]
Seems everything passes?  So I think this patch is probably good?

**Comment by hmaarrfk** [comment]
Yeah, generally I would like to have some green light from an upstream dev. Is there anything else to test with?

**Comment by djhoese** [comment]
I ran this PR (build 4 on @hmaarrfk anaconda.org channel) against all of Satpy's tests which include a few tests using pylibtiff on top of C libtiff to write custom TIFF files. Tests where build 2 from #49 seemed to seg fault now seem to pass on appveyor. Build log for the interested: https://ci.appveyor.com/project/pytroll/satpy/builds/29905441

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Thanks for doing that! I removed much of the regression tests from here so as to avoid a circular dependency. We can try them again once 4.2 is likely released with a patched up CMakeLists file.

**Comment by ocefpaf** [comment]
@hmaarrfk sorry for not following up on your work here. Is this ready to be merged?

**Comment by hmaarrfk** [comment]
Yeah. It is. I commented out the circular dependency testing.

**Comment by ocefpaf** [comment]
@hmaarrfk sorry but I ended up merging #48 first and now this one needs a rebase. If you don't have time for it I can port you patch later in a new PR.

**Comment by hmaarrfk** [comment]
seems like you pulled a package. do you still want me to rebase?

**Comment by hmaarrfk** [comment]
do you want me to test thing with gdal? can you provide the tests for the test section?

**Comment by ocefpaf** [comment]
Yeah, let's rebase and roll both changes at once. We'll have to put a migrator first though.

**Comment by hmaarrfk** [comment]
@ocefpaf did you want to merge this again with things cleaned? Seems like OSX is failing my downstream tests, but that seems to be due to some changes in `tifffile` that are kinda out of my control at this stage.

**Comment by ocefpaf** [comment]
Yeah, let's give it a go. Thanks @hmaarrfk!

**Comment by hmaarrfk** [comment]
opps. did you want me to remove the downstream tests?

**Comment by ocefpaf** [comment]
> opps. did you want me to remove the downstream tests?

Nope. I kind of liked them ;-p

**Comment by hmaarrfk** [comment]
then i think i need a build number bump.

**Comment by ocefpaf** [comment]
> then i think i need a build number bump.

Missed that! Sorry.

**Pull request merged**
