### PR TITLE
Patch win unix compat

### PR DESCRIPTION
**Pull request by hmaarrfk**
https://github.com/conda-forge/lcms2-feedstock/pull/3#discussion_r362735346
@kmilos

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Not too sure how this affects abi compatibility, but this used to be the default in 4.0

This means that 4.1 did break ABI compatibility on windows, but that change went on silently.

**Comment by djhoese** [comment]
I can't be sure yet, but I think this new build is breaking libtiff (the python package on PyPI) being able to use libtiff (the C library on conda-forge) on Appveyor. I'll try forcing the old build and see if that helps.

**Comment by hmaarrfk** [comment]
This may be true. :/ We might have to revert.

**Comment by djhoese** [comment]
Forcing build 1 (this PR is build 2) gets me further in my testing on appveyor. I'm also in dependency hell with my CI environment trying to install numpy 1.18 from PyPI and it breaking things which is what the above referenced commit got to. Using this PR's build seems to cause a segmentation fault of sorts. The appveyor log just goes from test output to stating the exit status of the appveyor script(s).

**Comment by hmaarrfk** [comment]
can you wait on numpy 1.18?

Reverting htis in an other PR.

**Comment by djhoese** [comment]
Sorry for the late reply. I came down with a cold and it hit me hard Friday night.

And yes, I can hold off on numpy 1.18, it wasn't something I actually want but has become the new default "stable" version used by astropy's ci-helpers tool. Things seem to be passing with build 1 on appveyor.

**Comment by hmaarrfk** [comment]
FYI, build 3 has been released, reverting build 2, so the solver should find that by default now.

**Comment by djhoese** [comment]
Yep, build 3 works for me. Thanks. Let me know when the next build of this PR is available and i can try it out.

**Comment by hmaarrfk** [comment]
If you are super inclined you can adding my channel

mark.harfouche
 https://anaconda.org/mark.harfouche/libtiff/files

It has build 4, which is the same as the live PR i have 
https://github.com/conda-forge/libtiff-feedstock/pull/51

That said, that PR does quite a bit more testing, so it should be safer ;)

**Pull request merged**
