### PR TITLE
Remove jbig

### PR DESCRIPTION
**Pull request by hmaarrfk**
@kmilos did you particularly need `jbig` or were you adding this for "completeness"

while we figure out a gpl/nongpl free, i would prefer to remove the GPL status, while we remedy the situation later.

Closes https://github.com/conda-forge/libtiff-feedstock/issues/74

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmilos** [comment]
It was to enable all possible features should someone need it. I personally don't.

**Comment by jakirkham** [comment]
Maybe we can do a split package?

Would this impact any downstream packages that were built against jbig version?

**Comment by bryan-hunt** [comment]
Packages built against the jbig version need to look at their licenses - about the only way to get around GPL propagation is to fork a separate process and scrape the output from it.

**Comment by jakirkham** [comment]
Not asking about the licensing so much as ABI stability. IOW is there a risk of downstream binaries referencing symbols prior to this change now run into missing symbol errors after?

**Comment by hmaarrfk** [comment]
@jakirkham this is honestly the reason why I've held off on these GPL/gplfree variants.

Inspecting this library, it seems that:

1. It is accidentally re-exporting the symbols from the jbig library itself.

```
                 w _ITM_registerTMCloneTable
0000000000054cc0 T jbg_ceil_half
000000000005a670 T jbg_dec_free
000000000005a450 T jbg_dec_getheight
000000000005a4a0 T jbg_dec_getimage
000000000005a510 T jbg_dec_getsize
000000000005a5b0 T jbg_dec_getsize_merged
000000000005a400 T jbg_dec_getwidth
0000000000059600 T jbg_dec_in
0000000000059590 T jbg_dec_init
00000000000595e0 T jbg_dec_maxsize
000000000005a9d0 T jbg_dec_merge_planes
0000000000058650 T jbg_dppriv2int
00000000000593a0 T jbg_enc_free
0000000000058080 T jbg_enc_init
00000000000582c0 T jbg_enc_layers
00000000000582f0 T jbg_enc_lrange
0000000000058250 T jbg_enc_lrlmax
0000000000058320 T jbg_enc_options
0000000000058930 T jbg_enc_out
0000000000058360 T jbg_int2dppriv
000000000005ad60 T jbg_newlen
000000000005ac60 T jbg_next_pscdms
000000000005a7a0 T jbg_split_planes
0000000000059560 T jbg_strerror
0000000000058050 T jbg_stripes
0000000000080800 R jbg_version
```

2. There is at least one TIFF symbol that is exported that would otherwise not exist if JBIG support was missing:
```
0000000000033d90 T TIFFInitJBIG
```

Honestly, I kinda do want to get this thing through, but I'm not sure how to address the pinnings, even if I were to write a repo-data patch.

**Comment by hmaarrfk** [comment]
I'm going to test this PR locally today and report if there are any issues.

Otherwise, we can likely patch it so that the symbol exists, but returns an error:
https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_codec.c#L112

as it does when it is not exported and tried to get used by an end user.

However, it seems that user's aren't "supposed" to use this and rather refer to the codecs. Libtiff will check if they are configured at runtime.

**Comment by hmaarrfk** [comment]
and tiffile i guess.

**Comment by hmaarrfk** [comment]
@jakirkham i think this should be relatively safe to include. Do you want to try using `donwstreams` on a few packages to make sure?

**Comment by hmaarrfk** [comment]
my current hypothesis is that jo oackage on co da forge used those symbols and as such, there is no need to do any kind of patching or migrator.

**Comment by hmaarrfk** [comment]
seems like we had previous issues with this feedstock that cauesd us to add "downstreams" I'm updating the opencv one and I feel much more confident that this is going to be OK.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
