### PR TITLE
Use downstreams instead of manually testing downstream packages

### PR DESCRIPTION
**Pull request by hmaarrfk**
Redo:  Fixup tests for OSX #57

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@ocefpaf this is ready for review

**Comment by hmaarrfk** [comment]
@ocefpaf I'm hoping I can help move the migrations forward on this repository. IT is blocking a few other builds from going through. Let me know if I can help.

**Review by ocefpaf — APPROVED** [review]
LGTM

**Pull request merged**
